export const countries = [
    { "name": "Afghanistan", "code": "AF", "dial": "+93", "len": 9 },
    { "name": "Åland Islands", "code": "AX", "dial": "+358", "len": 10 },
    { "name": "Albania", "code": "AL", "dial": "+355", "len": 9 },
    { "name": "Algeria", "code": "DZ", "dial": "+213", "len": 9 },
    { "name": "American Samoa", "code": "AS", "dial": "+1684", "len": 7 },
    { "name": "Andorra", "code": "AD", "dial": "+376", "len": 6 },
    { "name": "Angola", "code": "AO", "dial": "+244", "len": 9 },
    { "name": "Anguilla", "code": "AI", "dial": "+1264", "len": 7 },
    { "name": "Antarctica", "code": "AQ", "dial": "+672", "len": 6 },
    { "name": "Antigua and Barbuda", "code": "AG", "dial": "+1268", "len": 7 },
    { "name": "Argentina", "code": "AR", "dial": "+54", "len": 10 },
    { "name": "Armenia", "code": "AM", "dial": "+374", "len": 8 },
    { "name": "Aruba", "code": "AW", "dial": "+297", "len": 7 },
    { "name": "Australia", "code": "AU", "dial": "+61", "len": 9 },
    { "name": "Austria", "code": "AT", "dial": "+43", "len": 10 },
    { "name": "Azerbaijan", "code": "AZ", "dial": "+994", "len": 9 },
    { "name": "Bahamas", "code": "BS", "dial": "+1242", "len": 7 },
    { "name": "Bahrain", "code": "BH", "dial": "+973", "len": 8 },
    { "name": "Bangladesh", "code": "BD", "dial": "+880", "len": 10 },
    { "name": "Barbados", "code": "BB", "dial": "+1246", "len": 7 },
    { "name": "Belarus", "code": "BY", "dial": "+375", "len": 9 },
    { "name": "Belgium", "code": "BE", "dial": "+32", "len": 9 },
    { "name": "Belize", "code": "BZ", "dial": "+501", "len": 7 },
    { "name": "Benin", "code": "BJ", "dial": "+229", "len": 8 },
    { "name": "Bermuda", "code": "BM", "dial": "+1441", "len": 7 },
    { "name": "Bhutan", "code": "BT", "dial": "+975", "len": 8 },
    { "name": "Bolivia", "code": "BO", "dial": "+591", "len": 8 },
    { "name": "Bosnia and Herzegovina", "code": "BA", "dial": "+387", "len": 8 },
    { "name": "Botswana", "code": "BW", "dial": "+267", "len": 8 },
    { "name": "Bouvet Island", "code": "BV", "dial": "+47", "len": 8 },
    { "name": "Brazil", "code": "BR", "dial": "+55", "len": 11 },
    { "name": "British Indian Ocean Territory", "code": "IO", "dial": "+246", "len": 7 },
    { "name": "Brunei Darussalam", "code": "BN", "dial": "+673", "len": 7 },
    { "name": "Bulgaria", "code": "BG", "dial": "+359", "len": 9 },
    { "name": "Burkina Faso", "code": "BF", "dial": "+226", "len": 8 },
    { "name": "Burundi", "code": "BI", "dial": "+257", "len": 8 },
    { "name": "Cambodia", "code": "KH", "dial": "+855", "len": 9 },
    { "name": "Cameroon", "code": "CM", "dial": "+237", "len": 9 },
    { "name": "Canada", "code": "CA", "dial": "+1", "len": 10 },
    { "name": "Cape Verde", "code": "CV", "dial": "+238", "len": 7 },
    { "name": "Cayman Islands", "code": "KY", "dial": "+345", "len": 7 },
    { "name": "Central African Republic", "code": "CF", "dial": "+236", "len": 8 },
    { "name": "Chad", "code": "TD", "dial": "+235", "len": 8 },
    { "name": "Chile", "code": "CL", "dial": "+56", "len": 9 },
    { "name": "China", "code": "CN", "dial": "+86", "len": 11 },
    { "name": "Christmas Island", "code": "CX", "dial": "+61", "len": 9 },
    { "name": "Cocos (Keeling) Islands", "code": "CC", "dial": "+61", "len": 9 },
    { "name": "Colombia", "code": "CO", "dial": "+57", "len": 10 },
    { "name": "Comoros", "code": "KM", "dial": "+269", "len": 7 },
    { "name": "Congo", "code": "CG", "dial": "+242", "len": 9 },
    { "name": "Congo, Democratic Republic", "code": "CD", "dial": "+243", "len": 9 },
    { "name": "Cook Islands", "code": "CK", "dial": "+682", "len": 5 },
    { "name": "Costa Rica", "code": "CR", "dial": "+506", "len": 8 },
    { "name": "Cote d'Ivoire", "code": "CI", "dial": "+225", "len": 10 },
    { "name": "Croatia", "code": "HR", "dial": "+385", "len": 9 },
    { "name": "Cuba", "code": "CU", "dial": "+53", "len": 8 },
    { "name": "Cyprus", "code": "CY", "dial": "+357", "len": 8 },
    { "name": "Czech Republic", "code": "CZ", "dial": "+420", "len": 9 },
    { "name": "Denmark", "code": "DK", "dial": "+45", "len": 8 },
    { "name": "Djibouti", "code": "DJ", "dial": "+253", "len": 8 },
    { "name": "Dominica", "code": "DM", "dial": "+1767", "len": 7 },
    { "name": "Dominican Republic", "code": "DO", "dial": "+1849", "len": 7 },
    { "name": "Ecuador", "code": "EC", "dial": "+593", "len": 9 },
    { "name": "Egypt", "code": "EG", "dial": "+20", "len": 10 },
    { "name": "El Salvador", "code": "SV", "dial": "+503", "len": 8 },
    { "name": "Equatorial Guinea", "code": "GQ", "dial": "+240", "len": 9 },
    { "name": "Eritrea", "code": "ER", "dial": "+291", "len": 7 },
    { "name": "Estonia", "code": "EE", "dial": "+372", "len": 8 },
    { "name": "Ethiopia", "code": "ET", "dial": "+251", "len": 9 },
    { "name": "Falkland Islands", "code": "FK", "dial": "+500", "len": 5 },
    { "name": "Faroe Islands", "code": "FO", "dial": "+298", "len": 6 },
    { "name": "Fiji", "code": "FJ", "dial": "+679", "len": 7 },
    { "name": "Finland", "code": "FI", "dial": "+358", "len": 10 },
    { "name": "France", "code": "FR", "dial": "+33", "len": 9 },
    { "name": "French Guiana", "code": "GF", "dial": "+594", "len": 9 },
    { "name": "French Polynesia", "code": "PF", "dial": "+689", "len": 6 },
    { "name": "French Southern Territories", "code": "TF", "dial": "+262", "len": 9 },
    { "name": "Gabon", "code": "GA", "dial": "+241", "len": 7 },
    { "name": "Gambia", "code": "GM", "dial": "+220", "len": 7 },
    { "name": "Georgia", "code": "GE", "dial": "+995", "len": 9 },
    { "name": "Germany", "code": "DE", "dial": "+49", "len": 11 },
    { "name": "Ghana", "code": "GH", "dial": "+233", "len": 9 },
    { "name": "Gibraltar", "code": "GI", "dial": "+350", "len": 8 },
    { "name": "Greece", "code": "GR", "dial": "+30", "len": 10 },
    { "name": "Greenland", "code": "GL", "dial": "+299", "len": 6 },
    { "name": "Grenada", "code": "GD", "dial": "+1473", "len": 7 },
    { "name": "Guadeloupe", "code": "GP", "dial": "+590", "len": 9 },
    { "name": "Guam", "code": "GU", "dial": "+1671", "len": 7 },
    { "name": "Guatemala", "code": "GT", "dial": "+502", "len": 8 },
    { "name": "Guernsey", "code": "GG", "dial": "+44", "len": 10 },
    { "name": "Guinea", "code": "GN", "dial": "+224", "len": 9 },
    { "name": "Guinea-Bissau", "code": "GW", "dial": "+245", "len": 7 },
    { "name": "Guyana", "code": "GY", "dial": "+592", "len": 7 },
    { "name": "Haiti", "code": "HT", "dial": "+509", "len": 8 },
    { "name": "Heard Island and Mcdonald Islands", "code": "HM", "dial": "+672", "len": 6 },
    { "name": "Holy See", "code": "VA", "dial": "+379", "len": 6 },
    { "name": "Honduras", "code": "HN", "dial": "+504", "len": 8 },
    { "name": "Hong Kong", "code": "HK", "dial": "+852", "len": 8 },
    { "name": "Hungary", "code": "HU", "dial": "+36", "len": 9 },
    { "name": "Iceland", "code": "IS", "dial": "+354", "len": 7 },
    { "name": "India", "code": "IN", "dial": "+91", "len": 10 },
    { "name": "Indonesia", "code": "ID", "dial": "+62", "len": 11 },
    { "name": "Iran", "code": "IR", "dial": "+98", "len": 10 },
    { "name": "Iraq", "code": "IQ", "dial": "+964", "len": 10 },
    { "name": "Ireland", "code": "IE", "dial": "+353", "len": 9 },
    { "name": "Isle of Man", "code": "IM", "dial": "+44", "len": 10 },
    { "name": "Israel", "code": "IL", "dial": "+972", "len": 9 },
    { "name": "Italy", "code": "IT", "dial": "+39", "len": 10 },
    { "name": "Jamaica", "code": "JM", "dial": "+1876", "len": 7 },
    { "name": "Japan", "code": "JP", "dial": "+81", "len": 10 },
    { "name": "Jersey", "code": "JE", "dial": "+44", "len": 10 },
    { "name": "Jordan", "code": "JO", "dial": "+962", "len": 9 },
    { "name": "Kazakhstan", "code": "KZ", "dial": "+7", "len": 10 },
    { "name": "Kenya", "code": "KE", "dial": "+254", "len": 9 },
    { "name": "Kiribati", "code": "KI", "dial": "+686", "len": 8 },
    { "name": "North Korea", "code": "KP", "dial": "+850", "len": 10 },
    { "name": "South Korea", "code": "KR", "dial": "+82", "len": 10 },
    { "name": "Kosovo", "code": "XK", "dial": "+383", "len": 8 },
    { "name": "Kuwait", "code": "KW", "dial": "+965", "len": 8 },
    { "name": "Kyrgyzstan", "code": "KG", "dial": "+996", "len": 9 },
    { "name": "Laos", "code": "LA", "dial": "+856", "len": 8 },
    { "name": "Latvia", "code": "LV", "dial": "+371", "len": 8 },
    { "name": "Lebanon", "code": "LB", "dial": "+961", "len": 8 },
    { "name": "Lesotho", "code": "LS", "dial": "+266", "len": 8 },
    { "name": "Liberia", "code": "LR", "dial": "+231", "len": 8 },
    { "name": "Libya", "code": "LY", "dial": "+218", "len": 9 },
    { "name": "Liechtenstein", "code": "LI", "dial": "+423", "len": 7 },
    { "name": "Lithuania", "code": "LT", "dial": "+370", "len": 8 },
    { "name": "Luxembourg", "code": "LU", "dial": "+352", "len": 9 },
    { "name": "Macao", "code": "MO", "dial": "+853", "len": 8 },
    { "name": "Macedonia", "code": "MK", "dial": "+389", "len": 8 },
    { "name": "Madagascar", "code": "MG", "dial": "+261", "len": 9 },
    { "name": "Malawi", "code": "MW", "dial": "+265", "len": 9 },
    { "name": "Malaysia", "code": "MY", "dial": "+60", "len": 9 },
    { "name": "Maldives", "code": "MV", "dial": "+960", "len": 7 },
    { "name": "Mali", "code": "ML", "dial": "+223", "len": 8 },
    { "name": "Malta", "code": "MT", "dial": "+356", "len": 8 },
    { "name": "Marshall Islands", "code": "MH", "dial": "+692", "len": 7 },
    { "name": "Martinique", "code": "MQ", "dial": "+596", "len": 9 },
    { "name": "Mauritania", "code": "MR", "dial": "+222", "len": 8 },
    { "name": "Mauritius", "code": "MU", "dial": "+230", "len": 7 },
    { "name": "Mayotte", "code": "YT", "dial": "+262", "len": 9 },
    { "name": "Mexico", "code": "MX", "dial": "+52", "len": 10 },
    { "name": "Micronesia", "code": "FM", "dial": "+691", "len": 7 },
    { "name": "Moldova", "code": "MD", "dial": "+373", "len": 8 },
    { "name": "Monaco", "code": "MC", "dial": "+377", "len": 8 },
    { "name": "Mongolia", "code": "MN", "dial": "+976", "len": 8 },
    { "name": "Montenegro", "code": "ME", "dial": "+382", "len": 8 },
    { "name": "Montserrat", "code": "MS", "dial": "+1664", "len": 7 },
    { "name": "Morocco", "code": "MA", "dial": "+212", "len": 9 },
    { "name": "Mozambique", "code": "MZ", "dial": "+258", "len": 9 },
    { "name": "Myanmar", "code": "MM", "dial": "+95", "len": 9 },
    { "name": "Namibia", "code": "NA", "dial": "+264", "len": 9 },
    { "name": "Nauru", "code": "NR", "dial": "+674", "len": 7 },
    { "name": "Nepal", "code": "NP", "dial": "+977", "len": 10 },
    { "name": "Netherlands", "code": "NL", "dial": "+31", "len": 9 },
    { "name": "Netherlands Antilles", "code": "AN", "dial": "+599", "len": 8 },
    { "name": "New Caledonia", "code": "NC", "dial": "+687", "len": 6 },
    { "name": "New Zealand", "code": "NZ", "dial": "+64", "len": 10 },
    { "name": "Nicaragua", "code": "NI", "dial": "+505", "len": 8 },
    { "name": "Niger", "code": "NE", "dial": "+227", "len": 8 },
    { "name": "Nigeria", "code": "NG", "dial": "+234", "len": 10 },
    { "name": "Niue", "code": "NU", "dial": "+683", "len": 4 },
    { "name": "Norfolk Island", "code": "NF", "dial": "+672", "len": 6 },
    { "name": "Northern Mariana Islands", "code": "MP", "dial": "+1670", "len": 7 },
    { "name": "Norway", "code": "NO", "dial": "+47", "len": 8 },
    { "name": "Oman", "code": "OM", "dial": "+968", "len": 8 },
    { "name": "Pakistan", "code": "PK", "dial": "+92", "len": 10 },
    { "name": "Palau", "code": "PW", "dial": "+680", "len": 7 },
    { "name": "Palestinian Territory", "code": "PS", "dial": "+970", "len": 9 },
    { "name": "Panama", "code": "PA", "dial": "+507", "len": 8 },
    { "name": "Papua New Guinea", "code": "PG", "dial": "+675", "len": 8 },
    { "name": "Paraguay", "code": "PY", "dial": "+595", "len": 9 },
    { "name": "Peru", "code": "PE", "dial": "+51", "len": 9 },
    { "name": "Philippines", "code": "PH", "dial": "+63", "len": 10 },
    { "name": "Pitcairn", "code": "PN", "dial": "+64", "len": 10 },
    { "name": "Poland", "code": "PL", "dial": "+48", "len": 9 },
    { "name": "Portugal", "code": "PT", "dial": "+351", "len": 9 },
    { "name": "Puerto Rico", "code": "PR", "dial": "+1939", "len": 7 },
    { "name": "Qatar", "code": "QA", "dial": "+974", "len": 8 },
    { "name": "Romania", "code": "RO", "dial": "+40", "len": 9 },
    { "name": "Russia", "code": "RU", "dial": "+7", "len": 10 },
    { "name": "Rwanda", "code": "RW", "dial": "+250", "len": 9 },
    { "name": "Reunion", "code": "RE", "dial": "+262", "len": 9 },
    { "name": "Saint Barthelemy", "code": "BL", "dial": "+590", "len": 9 },
    { "name": "Saint Helena", "code": "SH", "dial": "+290", "len": 4 },
    { "name": "Saint Kitts and Nevis", "code": "KN", "dial": "+1869", "len": 7 },
    { "name": "Saint Lucia", "code": "LC", "dial": "+1758", "len": 7 },
    { "name": "Saint Martin", "code": "MF", "dial": "+590", "len": 9 },
    { "name": "Saint Pierre and Miquelon", "code": "PM", "dial": "+508", "len": 6 },
    { "name": "Saint Vincent", "code": "VC", "dial": "+1784", "len": 7 },
    { "name": "Samoa", "code": "WS", "dial": "+685", "len": 7 },
    { "name": "San Marino", "code": "SM", "dial": "+378", "len": 6 },
    { "name": "Sao Tome and Principe", "code": "ST", "dial": "+239", "len": 7 },
    { "name": "Saudi Arabia", "code": "SA", "dial": "+966", "len": 9 },
    { "name": "Senegal", "code": "SN", "dial": "+221", "len": 9 },
    { "name": "Serbia", "code": "RS", "dial": "+381", "len": 9 },
    { "name": "Seychelles", "code": "SC", "dial": "+248", "len": 7 },
    { "name": "Sierra Leone", "code": "SL", "dial": "+232", "len": 8 },
    { "name": "Singapore", "code": "SG", "dial": "+65", "len": 8 },
    { "name": "Slovakia", "code": "SK", "dial": "+421", "len": 9 },
    { "name": "Slovenia", "code": "SI", "dial": "+386", "len": 8 },
    { "name": "Solomon Islands", "code": "SB", "dial": "+677", "len": 7 },
    { "name": "Somalia", "code": "SO", "dial": "+252", "len": 8 },
    { "name": "South Africa", "code": "ZA", "dial": "+27", "len": 9 },
    { "name": "South Sudan", "code": "SS", "dial": "+211", "len": 9 },
    { "name": "South Georgia", "code": "GS", "dial": "+500", "len": 10 },
    { "name": "Spain", "code": "ES", "dial": "+34", "len": 9 },
    { "name": "Sri Lanka", "code": "LK", "dial": "+94", "len": 9 },
    { "name": "Sudan", "code": "SD", "dial": "+249", "len": 9 },
    { "name": "Suriname", "code": "SR", "dial": "+597", "len": 7 },
    { "name": "Svalbard and Jan Mayen", "code": "SJ", "dial": "+47", "len": 8 },
    { "name": "Eswatini", "code": "SZ", "dial": "+268", "len": 7 },
    { "name": "Sweden", "code": "SE", "dial": "+46", "len": 9 },
    { "name": "Switzerland", "code": "CH", "dial": "+41", "len": 9 },
    { "name": "Syria", "code": "SY", "dial": "+963", "len": 9 },
    { "name": "Taiwan", "code": "TW", "dial": "+886", "len": 9 },
    { "name": "Tajikistan", "code": "TJ", "dial": "+992", "len": 9 },
    { "name": "Tanzania", "code": "TZ", "dial": "+255", "len": 9 },
    { "name": "Thailand", "code": "TH", "dial": "+66", "len": 9 },
    { "name": "Timor-Leste", "code": "TL", "dial": "+670", "len": 7 },
    { "name": "Togo", "code": "TG", "dial": "+228", "len": 8 },
    { "name": "Tokelau", "code": "TK", "dial": "+690", "len": 4 },
    { "name": "Tonga", "code": "TO", "dial": "+676", "len": 7 },
    { "name": "Trinidad and Tobago", "code": "TT", "dial": "+1868", "len": 7 },
    { "name": "Tunisia", "code": "TN", "dial": "+216", "len": 8 },
    { "name": "Turkey", "code": "TR", "dial": "+90", "len": 10 },
    { "name": "Turkmenistan", "code": "TM", "dial": "+993", "len": 8 },
    { "name": "Turks and Caicos Islands", "code": "TC", "dial": "+1649", "len": 7 },
    { "name": "Tuvalu", "code": "TV", "dial": "+688", "len": 5 },
    { "name": "Uganda", "code": "UG", "dial": "+256", "len": 9 },
    { "name": "Ukraine", "code": "UA", "dial": "+380", "len": 9 },
    { "name": "United Arab Emirates", "code": "AE", "dial": "+971", "len": 9 },
    { "name": "United Kingdom", "code": "GB", "dial": "+44", "len": 10 },
    { "name": "United States", "code": "US", "dial": "+1", "len": 10 },
    { "name": "Uruguay", "code": "UY", "dial": "+598", "len": 8 },
    { "name": "Uzbekistan", "code": "UZ", "dial": "+998", "len": 9 },
    { "name": "Vanuatu", "code": "VU", "dial": "+678", "len": 7 },
    { "name": "Venezuela", "code": "VE", "dial": "+58", "len": 10 },
    { "name": "Vietnam", "code": "VN", "dial": "+84", "len": 9 },
    { "name": "Virgin Islands, British", "code": "VG", "dial": "+1284", "len": 7 },
    { "name": "Virgin Islands, U.S.", "code": "VI", "dial": "+1340", "len": 7 },
    { "name": "Wallis and Futuna", "code": "WF", "dial": "+681", "len": 6 },
    { "name": "Yemen", "code": "YE", "dial": "+967", "len": 9 },
    { "name": "Zambia", "code": "ZM", "dial": "+260", "len": 9 },
    { "name": "Zimbabwe", "code": "ZW", "dial": "+263", "len": 9 }
];
