import React, { useState, useEffect } from 'react';
import Layout from '@/components/Layout';
import SEOHead from '@/components/seo/SEOHead';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import {
    FileText,
    CheckCircle2,
    Download,
    AlertTriangle,
    ChevronRight,
    HelpCircle,
    Archive,
    Search,
    BookOpen,
    EyeOff,
    MonitorPlay
} from 'lucide-react';
import { Link } from 'react-router-dom';
import CTASection from '@/components/exams/CTASection';
import { usePageContent } from '@/hooks/usePageContent';
import CmsPageWrapper from '@/components/cms/CmsPageWrapper';
import EditableText from '@/components/cms/EditableText';
import FAQSchema from '@/components/seo/FAQSchema';
import KnowledgeHubSidebar from '@/components/exams/KnowledgeHubSidebar';
import { tolcLinks } from '@/lib/nav-links';
import { getBreadcrumbSchema } from '@/utils/seo-schemas';
import PageNavigation from '@/components/exams/PageNavigation';

const sections = [
    { id: 'overview', label: 'The Past Paper Problem' },
    { id: 'cisia', label: 'CISIA\'s Secrecy Policy' },
    { id: 'alternatives', label: 'Best Alternatives' },
    { id: 'faqs', label: 'FAQs' }
];

const faqs = [
    { question: 'Where can I download official past TOLC papers?', answer: 'You cannot. Unlike the IMAT or Cambridge exams, CISIA explicitly forbids the publication of past TOLC exams. The test is drawn from a massive, secret database of questions, meaning there is no single "past paper" for any given year.' },
    { question: 'Why are there no official past papers available?', answer: 'Because the TOLC is a CBT (Computer-Based Test) generated randomly for each student from a central database. Releasing past papers would compromise the integrity of the database, as questions are often reused across different sessions.' },
    { question: 'Are there any official sample questions at all?', answer: 'Yes. CISIA provides a very limited set of "Esercitazioni" (Practice Questions) on their official platform once you register. However, these are notoriously easier than the actual exam and do not provide a full, timed simulation.' },
    { question: 'I found a website selling past TOLC papers. Is it a scam?', answer: 'Most likely, yes. Anyone claiming to have official, full past papers is either lying or selling illegally obtained, incomplete memory recalls from past students. Do not pay for "leaked" past papers.' },
    { question: 'How am I supposed to practice without past papers?', answer: 'You must rely on high-quality mock tests generated by test-prep academies. These companies reverse-engineer the syllabus and gather post-exam student debriefs to create simulations that closely mirror the real exam\'s difficulty.' },
    { question: 'Are AlphaTest or Editest books good for practice questions?', answer: 'Yes, Italian test-prep publishers like AlphaTest, Editest, and Hoepli publish books containing thousands of practice questions (Quizzari). These are currently the closest physical equivalent to past papers, though they are usually only available in Italian.' },
    { question: 'Can I use IMAT past papers to study for the TOLC-MED?', answer: 'Yes, to an extent. The scientific syllabus (Biology, Chemistry) is highly overlapping. Practicing IMAT Biology questions is an excellent way to prepare for the Biology section of the TOLC-MED.' },
    { question: 'Does CISIA release the passing scores from previous years?', answer: 'CISIA does not. Passing scores (cutoffs) are published exclusively by the individual universities in their specific ranking lists (Graduatorie) after the admission window closes.' }
];

export default function TolcPreviousPapers() {
    const { getField } = usePageContent('tolc-previous-papers-2026');
    const [activeSection, setActiveSection] = useState('overview');

    useEffect(() => {
        const handleScroll = () => {
            const scrollPosition = window.scrollY + 100;
            for (const section of sections) {
                const element = document.getElementById(section.id);
                if (element && element.offsetTop <= scrollPosition && element.offsetTop + element.offsetHeight > scrollPosition) {
                    setActiveSection(section.id);
                    break;
                }
            }
        };
        window.addEventListener('scroll', handleScroll);
        return () => window.removeEventListener('scroll', handleScroll);
    }, []);

    return (
        <CmsPageWrapper slug="tolc-previous-papers-2026">
            <Layout
                variant="public"
                subNavigation={
                    <PageNavigation
                        sections={sections}
                        activeSection={activeSection}
                        setActiveSection={setActiveSection}
                    />
                }
            >
                <SEOHead
                    title="TOLC Past Papers & Practice Questions (PDF Download) 2026"
                    description="Why official TOLC past papers don't exist, CISIA's secrecy policy, and the best alternative resources for mock questions, PDFs, and realistic CBT practice."
                    keywords="TOLC past papers PDF, TOLC-I previous year papers, TOLC-MED practice questions, CISIA mock questions, download TOLC exam, TOLC sample papers"
                    schemas={[getBreadcrumbSchema([
                        { name: 'Home', item: '/' },
                        { name: 'TOLC Guide', item: '/tolc-exam-ultimate-guide-2026' },
                        { name: 'TOLC Previous Papers', item: '/tolc-previous-year-papers-pdf' }
                    ])]}
                    />

                <FAQSchema items={faqs} />

                <div className="bg-slate-50 dark:bg-slate-950 min-h-screen">
                    <main className="container mx-auto px-4 pt-0 pb-12">
                        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
                            
                            <div className="lg:col-span-4 hidden lg:block">
                                <div className="sticky top-32 self-start">
                                    <KnowledgeHubSidebar examType="tolc" />
                                </div>
                            </div>

                            <div className="lg:col-span-8 space-y-16">

                                {/* Hero */}
                                <section id="overview" className="scroll-mt-[120px]">
                                    <div className="inline-flex items-center gap-2 px-3 py-1 bg-rose-100 border border-rose-200 rounded-full text-rose-700 text-[10px] font-black uppercase tracking-widest mb-6 shadow-sm">
                                        <EyeOff size={12} className="text-rose-700" />
                                        The Hard Truth About TOLC Papers
                                    </div>

                                    <EditableText fieldKey="hero_headline" as="h1" className="text-5xl md:text-7xl font-black text-slate-900 leading-[1.1] mb-8">
                                        {getField('hero_headline', 'TOLC Past Papers: The Missing Resource')}
                                    </EditableText>

                                    <EditableText fieldKey="hero_desc" multiline as="p" className="text-xl md:text-2xl text-slate-600 leading-relaxed font-medium mb-10">
                                        {getField('hero_desc', "If you are endlessly searching Google for 'Official TOLC Past Papers PDF', you need to stop. They do not exist. Unlike the IMAT, where the Ministry releases the official PDF paper every year after the exam, CISIA operates the TOLC out of a highly guarded, randomized digital database. This page explains why you can't find past papers, warns against scams, and provides the best viable alternatives for your practice.")}
                                    </EditableText>

                                    <div className="bg-rose-50 border-l-4 border-rose-500 p-6 rounded-r-2xl mb-12">
                                        <div className="flex items-start gap-4">
                                            <AlertTriangle className="text-rose-500 shrink-0 mt-1" size={24} />
                                            <div>
                                                <h3 className="font-bold text-rose-900 text-lg mb-2">Scam Warning</h3>
                                                <p className="text-rose-800 text-sm leading-relaxed">
                                                    Do not pay money to websites claiming to sell "Official 2025 TOLC Past Papers". Because the test is digital and randomized, no single past paper exists. These sellers are either selling fake questions or highly fragmented, unreliable memory recalls from students.
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </section>

                                {/* CISIA Secrecy */}
                                <section id="cisia" className="scroll-mt-[120px]">
                                    <div className="flex items-center gap-4 mb-8">
                                        <div className="bg-slate-200 p-3 rounded-2xl">
                                            <Archive className="text-slate-700" size={28} />
                                        </div>
                                        <h2 className="text-3xl font-black text-slate-900">Why CISIA Hides the Questions</h2>
                                    </div>
                                    <p className="text-lg text-slate-600 leading-relaxed font-medium mb-8">
                                        The TOLC is a CBT (Computer-Based Test). When you sit down to take a TOLC-I, the computer randomly selects 50 questions from a database of tens of thousands of questions. The student sitting next to you receives a completely different exam.
                                    </p>
                                    <div className="grid md:grid-cols-2 gap-8">
                                        <div className="space-y-6">
                                            <h3 className="text-xl font-bold text-slate-800 border-b pb-2">Database Integrity</h3>
                                            <p className="text-sm text-slate-600 leading-relaxed">
                                                CISIA reuses questions across multiple sessions and years. If they published past papers, they would exhaust their database and students would simply memorize the answers rather than learning the core scientific concepts.
                                            </p>
                                        </div>
                                        <div className="space-y-6">
                                            <h3 className="text-xl font-bold text-slate-800 border-b pb-2">The "Equalization" Problem</h3>
                                            <p className="text-sm text-slate-600 leading-relaxed">
                                                For exams like TOLC-MED, releasing questions would break their statistical equalization algorithm, which relies on tracking how difficult a specific question is over thousands of blind attempts across different years.
                                            </p>
                                        </div>
                                    </div>
                                </section>

                                {/* Alternatives */}
                                <section id="alternatives" className="scroll-mt-[120px]">
                                    <div className="bg-slate-900 text-white rounded-[3rem] p-12 relative overflow-hidden">
                                        <div className="absolute top-0 right-0 p-8 opacity-5">
                                            <Search size={200} />
                                        </div>
                                        <div className="relative z-10">
                                            <h2 className="text-3xl font-black mb-6 flex items-center gap-4">
                                                <CheckCircle2 className="text-emerald-400" />
                                                The Best Alternatives
                                            </h2>
                                            <p className="text-lg text-slate-300 leading-relaxed font-medium mb-8 max-w-2xl">
                                                Since you can't download the official papers, here is exactly how successful students prepare for the exam.
                                            </p>
                                            
                                            <div className="space-y-6">
                                                <div className="bg-white/10 p-6 rounded-2xl border border-white/20 flex gap-4 items-start">
                                                    <div className="bg-indigo-500/20 p-3 rounded-xl shrink-0">
                                                        <MonitorPlay className="text-indigo-400" size={24} />
                                                    </div>
                                                    <div>
                                                        <h4 className="font-bold text-white text-lg mb-2">1. High-Quality Simulated Mocks</h4>
                                                        <p className="text-sm text-slate-300 leading-relaxed">
                                                            This is the gold standard. Use platforms (like ours) that offer full-length, reverse-engineered CBT simulations. This forces you to deal with the strict timers and negative marking that standard PDFs cannot replicate.
                                                        </p>
                                                    </div>
                                                </div>

                                                <div className="bg-white/10 p-6 rounded-2xl border border-white/20 flex gap-4 items-start">
                                                    <div className="bg-emerald-500/20 p-3 rounded-xl shrink-0">
                                                        <BookOpen className="text-emerald-400" size={24} />
                                                    </div>
                                                    <div>
                                                        <h4 className="font-bold text-white text-lg mb-2">2. Italian "Quizzari" (Question Banks)</h4>
                                                        <p className="text-sm text-slate-300 leading-relaxed">
                                                            Publishers like AlphaTest and Editest sell physical books with 3,000+ practice questions designed specifically for the TOLC syllabus. Even if you are taking the English TOLC, the Math and Logic concepts are universal.
                                                        </p>
                                                    </div>
                                                </div>

                                                <div className="bg-white/10 p-6 rounded-2xl border border-white/20 flex gap-4 items-start">
                                                    <div className="bg-rose-500/20 p-3 rounded-xl shrink-0">
                                                        <FileText className="text-rose-400" size={24} />
                                                    </div>
                                                    <div>
                                                        <h4 className="font-bold text-white text-lg mb-2">3. IMAT Past Papers (For TOLC-MED/F)</h4>
                                                        <p className="text-sm text-slate-300 leading-relaxed">
                                                            Because the IMAT is a public exam, all past papers since 2011 are available. The Biology and Chemistry sections of the IMAT are exceptionally good practice for the TOLC-MED and TOLC-F.
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </section>

                                {/* FAQs */}
                                <section id="faqs" className="scroll-mt-40">
                                    <div className="flex items-center gap-4 mb-12">
                                        <div className="bg-slate-200 p-3 rounded-2xl">
                                            <HelpCircle className="text-slate-600" size={32} />
                                        </div>
                                        <h2 className="text-4xl font-black text-slate-900">Frequently Asked Questions</h2>
                                    </div>
                                    <div className="space-y-6">
                                        {faqs.map((faq, i) => (
                                            <div key={i} className="bg-white p-8 rounded-3xl border border-slate-100 shadow-sm hover:shadow-md transition-shadow">
                                                <div className="text-xl font-black text-slate-900 mb-4 flex gap-4">
                                                    <span className="text-indigo-600">Q{i + 1}:</span>
                                                    <EditableText fieldKey={`faq_q_${i}`} as="div">
                                                        {getField(`faq_q_${i}`, faq.question)}
                                                    </EditableText>
                                                </div>
                                                <div className="text-slate-600 leading-relaxed font-medium pl-12 border-l-2 border-slate-50">
                                                    <EditableText fieldKey={`faq_a_${i}`} multiline as="div">
                                                        {getField(`faq_a_${i}`, faq.answer)}
                                                    </EditableText>
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                </section>

                                {/* Bottom Grid */}
                                <section className="pt-20 border-t border-slate-200">
                                    <h3 className="text-2xl font-black text-slate-900 mb-8">Explore the Full TOLC Cluster 📚</h3>
                                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                                        {tolcLinks.map((link, i) => (
                                            <Link key={i} to={link.path} className="group bg-white p-6 rounded-2xl border border-slate-100 shadow-sm hover:border-indigo-600 transition-colors flex items-center justify-between">
                                                <span className="font-bold text-slate-600 group-hover:text-slate-900 transition-colors">{link.label}</span>
                                                <ChevronRight className="text-slate-300 group-hover:text-indigo-600 group-hover:translate-x-1 transition-all" />
                                            </Link>
                                        ))}
                                    </div>
                                </section>

                                <CTASection fieldKeyPrefix="tolc_papers_cta" />
                            </div>
                        </div>
                    </main>
                </div>
            </Layout>
        </CmsPageWrapper>
    );
}
